export const MenuList=[
    {
        name: "首页",
        url:"home"
    },
    {
        name:"福瑞部落格",
        children:[
            {
                name:"相册",
                url:"album"
            },{
                name:"博客",
                url:"blog"
            }
        ]
    },{
        name:"福瑞的家",
        children:[
            {
                name:"福瑞",
                url:""
            },{
                name:"福吉",
                url:""
            },{
                name:"福临",
                url:""
            },{
                name:"福尔康",
                url:""
            },{
                name:"福尔泰",
                url:""
            },
        ]
    },{
        name:"福家种族分类",
        children:[
            {
                name:"橘猫",
                url:""
            },{
                name:"银渐层",
                url:""
            },{
                name:"金渐层",
                url:""
            }
        ]
    }
]